// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hairmony_api.Data;

#nullable disable

namespace hairmony_api.Migrations
{
    [DbContext(typeof(hairmonyContext))]
    [Migration("20250423022811_remapeando-models")]
    partial class remapeandomodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hairmony_api.Model.agendamentos", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("clienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("colaboradorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("concluido")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("data_ate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("data_de")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("salaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("servicoId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("agendamentos");
                });

            modelBuilder.Entity("hairmony_api.Model.clientes", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("celular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("salaoId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("hairmony_api.Model.colaboradores", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("salaoId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("colaboradores");
                });

            modelBuilder.Entity("hairmony_api.Model.salao", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("salao");
                });

            modelBuilder.Entity("hairmony_api.Model.servicos", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("duracao")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("preco")
                        .HasColumnType("numeric");

                    b.Property<Guid>("salaoId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("servicos");
                });
#pragma warning restore 612, 618
        }
    }
}
